"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
require("express-async-errors");
const express_1 = __importDefault(require("express"));
const users_routes_1 = require("./routes/users.routes");
require("reflect-metadata");
const error_1 = require("./error");
const login_routes_1 = require("./routes/login.routes");
const categories_routes_1 = require("./routes/categories.routes");
const realEstate_routes_1 = require("./routes/realEstate.routes");
const schedules_routes_1 = require("./routes/schedules.routes");
const app = (0, express_1.default)();
app.use(express_1.default.json());
app.use('/users', users_routes_1.userRoutes);
app.use('/login', login_routes_1.loginRoutes);
app.use('/categories', categories_routes_1.categoriesRoutes);
app.use('/realEstate', realEstate_routes_1.realEstateRoutes);
app.use('/schedules', schedules_routes_1.schedulesRoutes);
app.use(error_1.handleErros);
exports.default = app;
