"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Schedule = exports.RealEstate = exports.Category = exports.Address = exports.User = void 0;
const user_entity_1 = require("./user.entity");
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return user_entity_1.User; } });
const addresses_entity_1 = require("./addresses.entity");
Object.defineProperty(exports, "Address", { enumerable: true, get: function () { return addresses_entity_1.Address; } });
const categories_entity_1 = require("./categories.entity");
Object.defineProperty(exports, "Category", { enumerable: true, get: function () { return categories_entity_1.Category; } });
const real_estate_entity_1 = require("./real_estate.entity");
Object.defineProperty(exports, "RealEstate", { enumerable: true, get: function () { return real_estate_entity_1.RealEstate; } });
const schedules_entity_1 = require("./schedules.entity");
Object.defineProperty(exports, "Schedule", { enumerable: true, get: function () { return schedules_entity_1.Schedule; } });
